import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { ThemeProvider, Toaster } from "@ui/index";
import { cn } from "@ui/lib/utils";

import { ConvexClientProvider } from "@/providers/ConvexClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("antialiased", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          <ConvexClientProvider>{children}</ConvexClientProvider>
          <Toaster
            position="top-center"
            toastOptions={{ style: { textAlign: "center" } }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
