import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { ThemeProvider, Toaster } from "@ui/index";
import { cn } from "@ui/lib/utils";

import ConvexClientProvider from "./(components)/ConvexClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("bg-background flex-col antialiased", inter.className)}
      >
        <ConvexClientProvider>{children}</ConvexClientProvider>

        <Toaster
          position="top-center"
          toastOptions={{ style: { textAlign: "center" } }}
        />
      </body>
    </html>
  );
}
